server:
  port: 8010
user:
  userServiceUrl: http://127.0.0.1:8000/
spring:
  application:
    name: springcloud-consumer-movie
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true